// Generated by extract_picks.py from the betting pool xlsx — do not edit by hand
const POOL_DATA = {
 "title": "MM-Mundo 2026",
 "prizes": "Voitonjako: 1. 100€, 2. 60€, 3. 40€.",
 "participants": [
  "Jarkko",
  "Sanu",
  "Anni",
  "ilari",
  "Maija",
  "Otto",
  "Eero",
  "Eela",
  "Petja",
  "Niila",
  "Cole",
  "Jukkis",
  "Tuomas",
  "Sunnu",
  "Ryde",
  "Salla",
  "Tintti",
  "Jussi V",
  "Liisa",
  "Junnu"
 ],
 "matches": [
  {
   "row": 5,
   "group": "A",
   "homeFi": "Meksiko",
   "awayFi": "Etelä-Afrikka",
   "home": "Mexico",
   "away": "South Africa",
   "kickoff": "2026-06-11T19:00Z",
   "sheetResult": [
    2,
    0
   ],
   "picks": [
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     0
    ],
    [
     4,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 7,
   "group": "A",
   "homeFi": "Etelä-Korea",
   "awayFi": "Tšekki",
   "home": "South Korea",
   "away": "Czechia",
   "kickoff": "2026-06-12T02:00Z",
   "sheetResult": [
    2,
    1
   ],
   "picks": [
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     0
    ],
    [
     0,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     2
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 8,
   "group": "B",
   "homeFi": "Kanada",
   "awayFi": "Bosnia ja Hertsegovina",
   "home": "Canada",
   "away": "Bosnia-Herzegovina",
   "kickoff": "2026-06-12T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     0,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ]
   ]
  },
  {
   "row": 10,
   "group": "D",
   "homeFi": "USA",
   "awayFi": "Paraguay",
   "home": "United States",
   "away": "Paraguay",
   "kickoff": "2026-06-13T01:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     0,
     3
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     2
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     2
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ]
   ]
  },
  {
   "row": 11,
   "group": "C",
   "homeFi": "Brasilia",
   "awayFi": "Marokko",
   "home": "Brazil",
   "away": "Morocco",
   "kickoff": "2026-06-13T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     3,
     0
    ],
    [
     3,
     1
    ],
    [
     3,
     1
    ],
    [
     5,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     2
    ],
    [
     2,
     1
    ],
    [
     0,
     1
    ],
    [
     2,
     2
    ],
    [
     3,
     2
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 13,
   "group": "D",
   "homeFi": "Australia",
   "awayFi": "Turkki",
   "home": "Australia",
   "away": "Türkiye",
   "kickoff": "2026-06-13T22:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     3
    ],
    [
     1,
     2
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     1
    ],
    [
     2,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ]
   ]
  },
  {
   "row": 14,
   "group": "C",
   "homeFi": "Haiti",
   "awayFi": "Skotlanti",
   "home": "Haiti",
   "away": "Scotland",
   "kickoff": "2026-06-14T01:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     3
    ],
    [
     1,
     2
    ],
    [
     0,
     3
    ],
    [
     0,
     3
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     2,
     3
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 15,
   "group": "B",
   "homeFi": "Qatar",
   "awayFi": "Sveitsi",
   "home": "Qatar",
   "away": "Switzerland",
   "kickoff": "2026-06-14T04:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     4
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     3
    ],
    [
     0,
     3
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     2,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     0,
     3
    ],
    [
     1,
     3
    ],
    [
     0,
     3
    ]
   ]
  },
  {
   "row": 16,
   "group": "E",
   "homeFi": "Saksa",
   "awayFi": "Curaçao",
   "home": "Germany",
   "away": "Curaçao",
   "kickoff": "2026-06-14T17:00Z",
   "sheetResult": null,
   "picks": [
    [
     4,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     4,
     2
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     6,
     0
    ],
    [
     4,
     1
    ],
    [
     4,
     0
    ],
    [
     4,
     1
    ],
    [
     4,
     0
    ],
    [
     4,
     0
    ],
    [
     7,
     0
    ],
    [
     4,
     1
    ],
    [
     4,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     4,
     0
    ],
    [
     4,
     0
    ],
    [
     4,
     0
    ]
   ]
  },
  {
   "row": 17,
   "group": "E",
   "homeFi": "Norsunluurannikko",
   "awayFi": "Ecuador",
   "home": "Ivory Coast",
   "away": "Ecuador",
   "kickoff": "2026-06-14T20:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     2
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     3,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 19,
   "group": "F",
   "homeFi": "Hollanti",
   "awayFi": "Japani",
   "home": "Netherlands",
   "away": "Japan",
   "kickoff": "2026-06-14T23:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     0,
     1
    ],
    [
     3,
     1
    ],
    [
     2,
     2
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     0,
     1
    ],
    [
     2,
     1
    ],
    [
     3,
     2
    ],
    [
     2,
     2
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 20,
   "group": "F",
   "homeFi": "Ruotsi",
   "awayFi": "Tunisia",
   "home": "Sweden",
   "away": "Tunisia",
   "kickoff": "2026-06-15T02:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     0,
     0
    ],
    [
     1,
     2
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 21,
   "group": "H",
   "homeFi": "Espanja",
   "awayFi": "Kap Verde",
   "home": "Spain",
   "away": "Cape Verde",
   "kickoff": "2026-06-15T16:00Z",
   "sheetResult": null,
   "picks": [
    [
     4,
     0
    ],
    [
     3,
     1
    ],
    [
     3,
     0
    ],
    [
     5,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     4,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     4,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     2
    ],
    [
     4,
     1
    ],
    [
     3,
     0
    ],
    [
     4,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ]
   ]
  },
  {
   "row": 22,
   "group": "G",
   "homeFi": "Belgia",
   "awayFi": "Egypti",
   "home": "Belgium",
   "away": "Egypt",
   "kickoff": "2026-06-15T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     3,
     1
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     2
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ]
   ]
  },
  {
   "row": 24,
   "group": "H",
   "homeFi": "Saudi-Arabia",
   "awayFi": "Uruguay",
   "home": "Saudi Arabia",
   "away": "Uruguay",
   "kickoff": "2026-06-15T22:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     3
    ],
    [
     1,
     2
    ],
    [
     0,
     3
    ],
    [
     1,
     0
    ],
    [
     0,
     2
    ],
    [
     1,
     0
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     3
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 25,
   "group": "G",
   "homeFi": "Iran",
   "awayFi": "Uusi-Seelanti",
   "home": "Iran",
   "away": "New Zealand",
   "kickoff": "2026-06-16T01:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     0,
     0
    ],
    [
     0,
     1
    ],
    [
     1,
     0
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     0,
     2
    ],
    [
     1,
     0
    ],
    [
     0,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ]
   ]
  },
  {
   "row": 26,
   "group": "I",
   "homeFi": "Ranska",
   "awayFi": "Senegal",
   "home": "France",
   "away": "Senegal",
   "kickoff": "2026-06-16T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     4,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     4,
     1
    ],
    [
     2,
     1
    ],
    [
     3,
     2
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 28,
   "group": "I",
   "homeFi": "Irak",
   "awayFi": "Norja",
   "home": "Iraq",
   "away": "Norway",
   "kickoff": "2026-06-16T22:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     4
    ],
    [
     0,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     3
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     5
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     3
    ],
    [
     1,
     3
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 29,
   "group": "J",
   "homeFi": "Argentiina",
   "awayFi": "Algeria",
   "home": "Argentina",
   "away": "Algeria",
   "kickoff": "2026-06-17T01:00Z",
   "sheetResult": null,
   "picks": [
    [
     4,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     4,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     0
    ],
    [
     5,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     4,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 30,
   "group": "J",
   "homeFi": "Itävalta",
   "awayFi": "Jordania",
   "home": "Austria",
   "away": "Jordan",
   "kickoff": "2026-06-17T04:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ]
   ]
  },
  {
   "row": 31,
   "group": "K",
   "homeFi": "Portugali",
   "awayFi": "Kongon DR",
   "home": "Portugal",
   "away": "Congo DR",
   "kickoff": "2026-06-17T17:00Z",
   "sheetResult": null,
   "picks": [
    [
     4,
     0
    ],
    [
     1,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     4,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     5,
     1
    ],
    [
     1,
     0
    ],
    [
     3,
     0
    ],
    [
     4,
     1
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     0,
     0
    ],
    [
     4,
     0
    ],
    [
     3,
     0
    ]
   ]
  },
  {
   "row": 32,
   "group": "L",
   "homeFi": "Englanti",
   "awayFi": "Kroatia",
   "home": "England",
   "away": "Croatia",
   "kickoff": "2026-06-17T20:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     2
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     2
    ],
    [
     1,
     2
    ]
   ]
  },
  {
   "row": 34,
   "group": "L",
   "homeFi": "Ghana",
   "awayFi": "Panama",
   "home": "Ghana",
   "away": "Panama",
   "kickoff": "2026-06-17T23:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     2
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 35,
   "group": "K",
   "homeFi": "Uzbekistan",
   "awayFi": "Kolumbia",
   "home": "Uzbekistan",
   "away": "Colombia",
   "kickoff": "2026-06-18T02:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     1
    ],
    [
     2,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     0
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     3,
     1
    ],
    [
     1,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 36,
   "group": "A",
   "homeFi": "Tšekki",
   "awayFi": "Etelä-Afrikka",
   "home": "Czechia",
   "away": "South Africa",
   "kickoff": "2026-06-18T16:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     2
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ]
   ]
  },
  {
   "row": 37,
   "group": "B",
   "homeFi": "Sveitsi",
   "awayFi": "Bosnia ja Hertsegovina",
   "home": "Switzerland",
   "away": "Bosnia-Herzegovina",
   "kickoff": "2026-06-18T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     5,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     0
    ],
    [
     3,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     2
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ]
   ]
  },
  {
   "row": 39,
   "group": "B",
   "homeFi": "Kanada",
   "awayFi": "Qatar",
   "home": "Canada",
   "away": "Qatar",
   "kickoff": "2026-06-18T22:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     0
    ],
    [
     2,
     2
    ],
    [
     1,
     0
    ],
    [
     1,
     2
    ],
    [
     0,
     0
    ],
    [
     2,
     0
    ],
    [
     0,
     0
    ],
    [
     0,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 40,
   "group": "A",
   "homeFi": "Meksiko",
   "awayFi": "Etelä-Korea",
   "home": "Mexico",
   "away": "South Korea",
   "kickoff": "2026-06-19T01:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     0,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     2
    ],
    [
     1,
     2
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ]
   ]
  },
  {
   "row": 41,
   "group": "D",
   "homeFi": "USA",
   "awayFi": "Australia",
   "home": "United States",
   "away": "Australia",
   "kickoff": "2026-06-19T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     0,
     0
    ],
    [
     1,
     2
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 43,
   "group": "C",
   "homeFi": "Skotlanti",
   "awayFi": "Marokko",
   "home": "Scotland",
   "away": "Morocco",
   "kickoff": "2026-06-19T22:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     2,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     0
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 44,
   "group": "C",
   "homeFi": "Brasilia",
   "awayFi": "Haiti",
   "home": "Brazil",
   "away": "Haiti",
   "kickoff": "2026-06-20T01:00Z",
   "sheetResult": null,
   "picks": [
    [
     4,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ],
    [
     3,
     0
    ],
    [
     6,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     4,
     0
    ],
    [
     3,
     0
    ],
    [
     5,
     0
    ],
    [
     4,
     1
    ],
    [
     1,
     1
    ],
    [
     3,
     0
    ],
    [
     4,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     0
    ],
    [
     4,
     0
    ]
   ]
  },
  {
   "row": 45,
   "group": "D",
   "homeFi": "Turkki",
   "awayFi": "Paraguay",
   "home": "Türkiye",
   "away": "Paraguay",
   "kickoff": "2026-06-20T04:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     2,
     2
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 46,
   "group": "F",
   "homeFi": "Hollanti",
   "awayFi": "Ruotsi",
   "home": "Netherlands",
   "away": "Sweden",
   "kickoff": "2026-06-20T17:00Z",
   "sheetResult": null,
   "picks": [
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     0
    ],
    [
     2,
     2
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 47,
   "group": "E",
   "homeFi": "Saksa",
   "awayFi": "Norsunluurannikko",
   "home": "Germany",
   "away": "Ivory Coast",
   "kickoff": "2026-06-20T20:00Z",
   "sheetResult": null,
   "picks": [
    [
     4,
     0
    ],
    [
     1,
     1
    ],
    [
     3,
     0
    ],
    [
     6,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ],
    [
     4,
     1
    ],
    [
     3,
     1
    ],
    [
     3,
     1
    ],
    [
     3,
     0
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 49,
   "group": "E",
   "homeFi": "Ecuador",
   "awayFi": "Curaçao",
   "home": "Ecuador",
   "away": "Curaçao",
   "kickoff": "2026-06-21T00:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     0,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     0,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     3,
     0
    ]
   ]
  },
  {
   "row": 50,
   "group": "F",
   "homeFi": "Tunisia",
   "awayFi": "Japani",
   "home": "Tunisia",
   "away": "Japan",
   "kickoff": "2026-06-21T04:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ]
   ]
  },
  {
   "row": 51,
   "group": "H",
   "homeFi": "Espanja",
   "awayFi": "Saudi-Arabia",
   "home": "Spain",
   "away": "Saudi Arabia",
   "kickoff": "2026-06-21T16:00Z",
   "sheetResult": null,
   "picks": [
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     4,
     0
    ],
    [
     5,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     4,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     1
    ],
    [
     4,
     1
    ],
    [
     2,
     0
    ],
    [
     4,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ]
   ]
  },
  {
   "row": 52,
   "group": "G",
   "homeFi": "Belgia",
   "awayFi": "Iran",
   "home": "Belgium",
   "away": "Iran",
   "kickoff": "2026-06-21T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     0,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 54,
   "group": "H",
   "homeFi": "Uruguay",
   "awayFi": "Kap Verde",
   "home": "Uruguay",
   "away": "Cape Verde",
   "kickoff": "2026-06-21T22:00Z",
   "sheetResult": null,
   "picks": [
    [
     3,
     0
    ],
    [
     4,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     5,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     2
    ],
    [
     0,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 55,
   "group": "G",
   "homeFi": "Uusi-Seelanti",
   "awayFi": "Egypti",
   "home": "New Zealand",
   "away": "Egypt",
   "kickoff": "2026-06-22T01:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     0,
     0
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 56,
   "group": "J",
   "homeFi": "Argentiina",
   "awayFi": "Itävalta",
   "home": "Argentina",
   "away": "Austria",
   "kickoff": "2026-06-22T17:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     4,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ]
   ]
  },
  {
   "row": 58,
   "group": "I",
   "homeFi": "Ranska",
   "awayFi": "Irak",
   "home": "France",
   "away": "Iraq",
   "kickoff": "2026-06-22T21:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     0
    ],
    [
     4,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     3,
     1
    ],
    [
     3,
     1
    ],
    [
     5,
     0
    ],
    [
     4,
     1
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     4,
     1
    ],
    [
     2,
     0
    ],
    [
     4,
     1
    ],
    [
     5,
     1
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     4,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ]
   ]
  },
  {
   "row": 59,
   "group": "I",
   "homeFi": "Norja",
   "awayFi": "Senegal",
   "home": "Norway",
   "away": "Senegal",
   "kickoff": "2026-06-23T00:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     0
    ],
    [
     1,
     2
    ],
    [
     3,
     1
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     3,
     2
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     2
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 60,
   "group": "J",
   "homeFi": "Jordania",
   "awayFi": "Algeria",
   "home": "Jordan",
   "away": "Algeria",
   "kickoff": "2026-06-23T03:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     3
    ],
    [
     1,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     3
    ],
    [
     2,
     2
    ],
    [
     2,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 61,
   "group": "K",
   "homeFi": "Portugali",
   "awayFi": "Uzbekistan",
   "home": "Portugal",
   "away": "Uzbekistan",
   "kickoff": "2026-06-23T17:00Z",
   "sheetResult": null,
   "picks": [
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     3,
     0
    ]
   ]
  },
  {
   "row": 62,
   "group": "L",
   "homeFi": "Englanti",
   "awayFi": "Ghana",
   "home": "England",
   "away": "Ghana",
   "kickoff": "2026-06-23T20:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     4,
     0
    ],
    [
     3,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ],
    [
     3,
     0
    ],
    [
     1,
     1
    ],
    [
     3,
     1
    ],
    [
     4,
     0
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 64,
   "group": "L",
   "homeFi": "Panama",
   "awayFi": "Kroatia",
   "home": "Panama",
   "away": "Croatia",
   "kickoff": "2026-06-23T23:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     2
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     4
    ],
    [
     1,
     0
    ],
    [
     0,
     3
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     3
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 65,
   "group": "K",
   "homeFi": "Kolumbia",
   "awayFi": "Kongon DR",
   "home": "Colombia",
   "away": "Congo DR",
   "kickoff": "2026-06-24T02:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     0
    ],
    [
     2,
     2
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     2
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 66,
   "group": "B",
   "homeFi": "Kanada",
   "awayFi": "Sveitsi",
   "home": "Canada",
   "away": "Switzerland",
   "kickoff": "2026-06-24T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     0,
     3
    ],
    [
     1,
     3
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     0
    ],
    [
     2,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ]
   ]
  },
  {
   "row": 67,
   "group": "B",
   "homeFi": "Bosnia ja Hertsegovina",
   "awayFi": "Qatar",
   "home": "Bosnia-Herzegovina",
   "away": "Qatar",
   "kickoff": "2026-06-24T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     2
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     0,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     2
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 69,
   "group": "C",
   "homeFi": "Skotlanti",
   "awayFi": "Brasilia",
   "home": "Scotland",
   "away": "Brazil",
   "kickoff": "2026-06-24T22:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     3
    ],
    [
     1,
     3
    ],
    [
     1,
     4
    ],
    [
     0,
     2
    ],
    [
     0,
     3
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     3
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 70,
   "group": "C",
   "homeFi": "Marokko",
   "awayFi": "Haiti",
   "home": "Morocco",
   "away": "Haiti",
   "kickoff": "2026-06-24T22:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     3,
     0
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 71,
   "group": "A",
   "homeFi": "Meksiko",
   "awayFi": "Tšekki",
   "home": "Mexico",
   "away": "Czechia",
   "kickoff": "2026-06-25T01:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     2
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 72,
   "group": "A",
   "homeFi": "Etelä-Korea",
   "awayFi": "Etelä-Afrikka",
   "home": "South Korea",
   "away": "South Africa",
   "kickoff": "2026-06-25T01:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     3
    ],
    [
     1,
     2
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 73,
   "group": "E",
   "homeFi": "Ecuador",
   "awayFi": "Saksa",
   "home": "Ecuador",
   "away": "Germany",
   "kickoff": "2026-06-25T20:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     3
    ],
    [
     2,
     3
    ],
    [
     0,
     4
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     0
    ],
    [
     0,
     1
    ],
    [
     2,
     3
    ],
    [
     2,
     3
    ],
    [
     1,
     1
    ],
    [
     1,
     3
    ],
    [
     1,
     2
    ],
    [
     2,
     2
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 74,
   "group": "E",
   "homeFi": "Curaçao",
   "awayFi": "Norsunluurannikko",
   "home": "Curaçao",
   "away": "Ivory Coast",
   "kickoff": "2026-06-25T20:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     1,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     0
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     4
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     3
    ]
   ]
  },
  {
   "row": 76,
   "group": "F",
   "homeFi": "Tunisia",
   "awayFi": "Hollanti",
   "home": "Tunisia",
   "away": "Netherlands",
   "kickoff": "2026-06-25T23:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     3
    ],
    [
     2,
     0
    ],
    [
     1,
     3
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     4
    ],
    [
     1,
     3
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     3
    ],
    [
     1,
     2
    ],
    [
     0,
     0
    ]
   ]
  },
  {
   "row": 77,
   "group": "F",
   "homeFi": "Japani",
   "awayFi": "Ruotsi",
   "home": "Japan",
   "away": "Sweden",
   "kickoff": "2026-06-25T23:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     4,
     2
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 78,
   "group": "D",
   "homeFi": "USA",
   "awayFi": "Turkki",
   "home": "United States",
   "away": "Türkiye",
   "kickoff": "2026-06-26T02:00Z",
   "sheetResult": null,
   "picks": [
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     0,
     0
    ],
    [
     3,
     2
    ],
    [
     1,
     1
    ],
    [
     0,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     3,
     0
    ],
    [
     2,
     2
    ],
    [
     0,
     0
    ]
   ]
  },
  {
   "row": 79,
   "group": "D",
   "homeFi": "Paraguay",
   "awayFi": "Australia",
   "home": "Paraguay",
   "away": "Australia",
   "kickoff": "2026-06-26T02:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     0,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     2,
     2
    ],
    [
     1,
     0
    ]
   ]
  },
  {
   "row": 80,
   "group": "I",
   "homeFi": "Norja",
   "awayFi": "Ranska",
   "home": "Norway",
   "away": "France",
   "kickoff": "2026-06-26T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     0
    ],
    [
     1,
     3
    ],
    [
     1,
     1
    ],
    [
     0,
     3
    ],
    [
     1,
     3
    ],
    [
     1,
     3
    ],
    [
     2,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     2,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     1
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ]
   ]
  },
  {
   "row": 81,
   "group": "I",
   "homeFi": "Senegal",
   "awayFi": "Irak",
   "home": "Senegal",
   "away": "Iraq",
   "kickoff": "2026-06-26T19:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     3,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     3,
     1
    ],
    [
     3,
     1
    ],
    [
     0,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ]
   ]
  },
  {
   "row": 83,
   "group": "H",
   "homeFi": "Kap Verde",
   "awayFi": "Saudi-Arabia",
   "home": "Cape Verde",
   "away": "Saudi Arabia",
   "kickoff": "2026-06-27T00:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     2,
     0
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     2
    ],
    [
     0,
     0
    ]
   ]
  },
  {
   "row": 84,
   "group": "H",
   "homeFi": "Uruguay",
   "awayFi": "Espanja",
   "home": "Uruguay",
   "away": "Spain",
   "kickoff": "2026-06-27T00:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     3
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     3
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 85,
   "group": "G",
   "homeFi": "Uusi-Seelanti",
   "awayFi": "Belgia",
   "home": "New Zealand",
   "away": "Belgium",
   "kickoff": "2026-06-27T03:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     2,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     3
    ],
    [
     0,
     3
    ]
   ]
  },
  {
   "row": 86,
   "group": "G",
   "homeFi": "Egypti",
   "awayFi": "Iran",
   "home": "Egypt",
   "away": "Iran",
   "kickoff": "2026-06-27T03:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     2
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     0
    ],
    [
     0,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ]
   ]
  },
  {
   "row": 88,
   "group": "L",
   "homeFi": "Panama",
   "awayFi": "Englanti",
   "home": "Panama",
   "away": "England",
   "kickoff": "2026-06-27T21:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     3
    ],
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     1,
     3
    ],
    [
     2,
     3
    ],
    [
     0,
     5
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     5
    ],
    [
     0,
     4
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     3
    ],
    [
     0,
     3
    ]
   ]
  },
  {
   "row": 89,
   "group": "L",
   "homeFi": "Kroatia",
   "awayFi": "Ghana",
   "home": "Croatia",
   "away": "Ghana",
   "kickoff": "2026-06-27T21:00Z",
   "sheetResult": null,
   "picks": [
    [
     1,
     0
    ],
    [
     3,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     1,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     2,
     0
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     3,
     1
    ],
    [
     2,
     1
    ]
   ]
  },
  {
   "row": 90,
   "group": "K",
   "homeFi": "Kolumbia",
   "awayFi": "Portugali",
   "home": "Colombia",
   "away": "Portugal",
   "kickoff": "2026-06-27T23:30Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     2
    ],
    [
     1,
     2
    ]
   ]
  },
  {
   "row": 91,
   "group": "K",
   "homeFi": "Kongon DR",
   "awayFi": "Uzbekistan",
   "home": "Congo DR",
   "away": "Uzbekistan",
   "kickoff": "2026-06-27T23:30Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     1
    ],
    [
     0,
     2
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     2,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     0
    ],
    [
     1,
     0
    ],
    [
     0,
     0
    ],
    [
     1,
     1
    ],
    [
     0,
     0
    ],
    [
     0,
     0
    ],
    [
     0,
     1
    ],
    [
     0,
     0
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     0
    ],
    [
     2,
     2
    ],
    [
     1,
     0
    ]
   ]
  },
  {
   "row": 92,
   "group": "J",
   "homeFi": "Jordania",
   "awayFi": "Argentiina",
   "home": "Jordan",
   "away": "Argentina",
   "kickoff": "2026-06-28T02:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     5
    ],
    [
     1,
     3
    ],
    [
     1,
     0
    ],
    [
     0,
     4
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     1,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     4
    ],
    [
     0,
     2
    ],
    [
     1,
     2
    ],
    [
     0,
     3
    ],
    [
     0,
     3
    ],
    [
     0,
     2
    ],
    [
     0,
     2
    ],
    [
     0,
     4
    ]
   ]
  },
  {
   "row": 93,
   "group": "J",
   "homeFi": "Algeria",
   "awayFi": "Itävalta",
   "home": "Algeria",
   "away": "Austria",
   "kickoff": "2026-06-28T02:00Z",
   "sheetResult": null,
   "picks": [
    [
     0,
     2
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     2
    ],
    [
     0,
     1
    ],
    [
     1,
     1
    ],
    [
     0,
     2
    ],
    [
     2,
     0
    ],
    [
     0,
     1
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     2,
     1
    ],
    [
     1,
     0
    ],
    [
     0,
     2
    ],
    [
     1,
     1
    ],
    [
     2,
     2
    ],
    [
     1,
     2
    ]
   ]
  }
 ],
 "specials": {
  "top8": {
   "Jarkko": [
    "Spain",
    "England",
    "Netherlands",
    "France",
    "Argentina",
    "Brazil",
    "Norway",
    "Germany"
   ],
   "Sanu": [
    "Germany",
    "Netherlands",
    "Uzbekistan",
    "Belgium",
    "Brazil",
    "Croatia",
    "England",
    "Portugal"
   ],
   "Anni": [
    "Germany",
    "Spain",
    "Netherlands",
    "England",
    "France",
    "Portugal",
    "Norway",
    "Argentina"
   ],
   "ilari": [
    "France",
    "Spain",
    "Argentina",
    "Portugal",
    "Germany",
    "England",
    "Brazil",
    "United States"
   ],
   "Maija": [
    "France",
    "Argentina",
    "Brazil",
    "England",
    "Spain",
    "Germany",
    "Netherlands",
    "Japan"
   ],
   "Otto": [
    "France",
    "Portugal",
    "Spain",
    "Argentina",
    "Brazil",
    "Germany",
    "England",
    "United States"
   ],
   "Eero": [
    "Germany",
    "France",
    "Norway",
    "Uruguay",
    "Spain",
    "Argentina",
    "Brazil",
    "Portugal"
   ],
   "Eela": [
    "France",
    "Spain",
    "Brazil",
    "England",
    "Portugal",
    "Germany",
    "Argentina",
    "Netherlands"
   ],
   "Petja": [
    "Spain",
    "Morocco",
    "England",
    "Argentina",
    "Brazil",
    "Germany",
    "Netherlands",
    "Mexico"
   ],
   "Niila": [
    "France",
    "Argentina",
    "Spain",
    "Germany",
    "Portugal",
    "United States",
    "Brazil",
    "England"
   ],
   "Cole": [
    "France",
    "Argentina",
    "Mexico",
    "Spain",
    "Germany",
    "England",
    "Brazil",
    "Netherlands"
   ],
   "Jukkis": [
    "Spain",
    "France",
    "Argentina",
    "England",
    "Japan",
    "Morocco",
    "Portugal",
    "Croatia"
   ],
   "Tuomas": [
    "England",
    "France",
    "Spain",
    "Portugal",
    "Norway",
    "Germany",
    "Netherlands",
    "Ivory Coast"
   ],
   "Sunnu": [
    "Brazil",
    "England",
    "France",
    "Portugal",
    "Germany",
    "Spain",
    "Netherlands",
    "Argentina"
   ],
   "Ryde": [
    "France",
    "Brazil",
    "Argentina",
    "Switzerland",
    "Spain",
    "Germany",
    "Norway",
    "England"
   ],
   "Salla": [
    "Spain",
    "France",
    "England",
    "Portugal",
    "Argentina",
    "Brazil",
    "Colombia",
    "Morocco"
   ],
   "Tintti": [
    "Brazil",
    "France",
    "England",
    "Spain",
    "Argentina",
    "Portugal",
    "Netherlands",
    "Uruguay"
   ],
   "Jussi V": [
    "Switzerland",
    "Brazil",
    "Netherlands",
    "France",
    "England",
    "Spain",
    "Germany",
    "Belgium"
   ],
   "Liisa": [
    "Netherlands",
    "France",
    "Brazil",
    "England",
    "Spain",
    "Belgium",
    "Argentina",
    "Portugal"
   ],
   "Junnu": [
    "Croatia",
    "Spain",
    "Germany",
    "Colombia",
    "England",
    "Brazil",
    "France",
    "Argentina"
   ]
  },
  "top4": {
   "Jarkko": [
    "Spain",
    "France",
    "Argentina",
    "Brazil"
   ],
   "Sanu": [
    "Netherlands",
    "France",
    "Portugal",
    "Croatia"
   ],
   "Anni": [
    "Brazil",
    "Spain",
    "Argentina",
    "England"
   ],
   "ilari": [
    "Argentina",
    "France",
    "Spain",
    "Portugal"
   ],
   "Maija": [
    "France",
    "Argentina",
    "England",
    "Brazil"
   ],
   "Otto": [
    "France",
    "Spain",
    "Portugal",
    "Brazil"
   ],
   "Eero": [
    "France",
    "Norway",
    "Spain",
    "Brazil"
   ],
   "Eela": [
    "France",
    "Spain",
    "Brazil",
    "England"
   ],
   "Petja": [
    "Mexico",
    "Spain",
    "England",
    "Brazil"
   ],
   "Niila": [
    "Spain",
    "England",
    "France",
    "Germany"
   ],
   "Cole": [
    "France",
    "Argentina",
    "Germany",
    "Spain"
   ],
   "Jukkis": [
    "Spain",
    "France",
    "Argentina",
    "England"
   ],
   "Tuomas": [
    "France",
    "Spain",
    "Norway",
    "Brazil"
   ],
   "Sunnu": [
    "Brazil",
    "France",
    "England",
    "Spain"
   ],
   "Ryde": [
    "Argentina",
    "Spain",
    "Germany",
    "France"
   ],
   "Salla": [
    "Spain",
    "France",
    "England",
    "Morocco"
   ],
   "Tintti": [
    "France",
    "England",
    "Brazil",
    "Netherlands"
   ],
   "Jussi V": [
    "England",
    "Spain",
    "France",
    "Brazil"
   ],
   "Liisa": [
    "France",
    "Spain",
    "England",
    "Portugal"
   ],
   "Junnu": [
    "Spain",
    "Colombia",
    "Brazil",
    "France"
   ]
  },
  "semiScorer": {
   "Jarkko": "Mbappe",
   "Sanu": "Luka Modric",
   "Anni": "Yamal",
   "ilari": "Dembele",
   "Maija": "Mbappé",
   "Otto": "Ronaldo",
   "Eero": "Olise",
   "Eela": "Yamal",
   "Petja": "Yamal",
   "Niila": "Mbappé",
   "Cole": "Lautaro Martinez",
   "Jukkis": "Mbappé",
   "Tuomas": "Michael Olise",
   "Sunnu": "Kane",
   "Ryde": "Kane",
   "Salla": "Mbappe",
   "Tintti": "Mbappé",
   "Jussi V": "Harry Kane",
   "Liisa": "Kane",
   "Junnu": "Doue"
  },
  "topScorer": {
   "Jarkko": "Mbappe",
   "Sanu": "Mbappé",
   "Anni": "Mbappé",
   "ilari": "Ronaldo",
   "Maija": "Mbappé",
   "Otto": "Ronaldo",
   "Eero": "Haaland",
   "Eela": "Yamal",
   "Petja": "Kane",
   "Niila": "Mbappé",
   "Cole": "Mbappé",
   "Jukkis": "Mbappé",
   "Tuomas": "Haaland",
   "Sunnu": "Mbappe",
   "Ryde": "Oyarzabal",
   "Salla": "Mbappe",
   "Tintti": "Mbappé",
   "Jussi V": "Mbappe",
   "Liisa": "Kane",
   "Junnu": "Luis Diaz"
  },
  "bronze": {
   "Jarkko": "Argentina",
   "Sanu": "England",
   "Anni": "Germany",
   "ilari": "Spain",
   "Maija": "Brazil",
   "Otto": "Argentina",
   "Eero": "Spain",
   "Eela": "England",
   "Petja": "England",
   "Niila": "Brazil",
   "Cole": "Spain",
   "Jukkis": "England",
   "Tuomas": "Norway",
   "Sunnu": "Spain",
   "Ryde": "Germany",
   "Salla": "England",
   "Tintti": "Netherlands",
   "Jussi V": "France",
   "Liisa": "Spain",
   "Junnu": "Colombia"
  },
  "finalLoser": {
   "Jarkko": "France",
   "Sanu": "Croatia",
   "Anni": "Spain",
   "ilari": "France",
   "Maija": "Argentina",
   "Otto": "France",
   "Eero": "Brazil",
   "Eela": "France",
   "Petja": "Brazil",
   "Niila": "England",
   "Cole": "Argentina",
   "Jukkis": "France",
   "Tuomas": "France",
   "Sunnu": "England",
   "Ryde": "France",
   "Salla": "Morocco",
   "Tintti": "England",
   "Jussi V": "Spain",
   "Liisa": "England",
   "Junnu": "Spain"
  },
  "champion": {
   "Jarkko": "Spain",
   "Sanu": "Portugal",
   "Anni": "England",
   "ilari": "Portugal",
   "Maija": "France",
   "Otto": "Portugal",
   "Eero": "France",
   "Eela": "Spain",
   "Petja": "Spain",
   "Niila": "France",
   "Cole": "France",
   "Jukkis": "Spain",
   "Tuomas": "England",
   "Sunnu": "Brazil",
   "Ryde": "Argentina",
   "Salla": "Spain",
   "Tintti": "France",
   "Jussi V": "England",
   "Liisa": "France",
   "Junnu": "France"
  }
 }
};
